blog/urls.py
from django.urls import path
from blog.apps import BlogConfig

from blog.views import ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='blog_list'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('distribution.urls', namespace='distribution')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='слаг')
    content = models.TextField(verbose_name='содержание')
    preview_image = models.ImageField(verbose_name='изображение')
    created_at = models.DateTimeField(verbose_name='дата создания', auto_now_add=True)
    is_published = models.BooleanField(verbose_name='опубликовано', default=True)
    views_counter = models.PositiveIntegerField(verbose_name='количество просмотров', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'статья блога'
        verbose_name_plural = 'статьи блога'

blog/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from blog.models import Article
from distribution.forms import StyleFormMixin


class ArticleForm(StyleFormMixin, ModelForm):
    """Форма для статей блога"""
    class Meta:
        model = Article
        fields = '__all__'
        exclude = ['views_counter', 'is_published', 'created_at', 'slug']

    def clean_title(self):
        """Функции для контроля содержимого статей"""
        cleaned_data = self.cleaned_data.get('title')

        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for each in forbidden_words:
            if each in cleaned_data:
                raise ValidationError('Извините, такой заголовок недопустим для статьи')

        return cleaned_data

    def clean_content(self):
        """Функции для контроля содержимого статей"""
        cleaned_data = self.cleaned_data.get('content')

        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for each in forbidden_words:
            if each in cleaned_data:
                raise ValidationError('Извините, такое содержание недопустимо для статьи')

        return cleaned_data

blog/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.forms import ArticleForm
from blog.models import Article
from distribution.services import get_articles_from_cache


class ArticleListView(ListView):
    model = Article

    def get_queryset(self):
        """Реализовано кэширование отдельных статей блога"""
        return get_articles_from_cache()


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        """Счетчик просмотров"""
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy("blog:blog_list")


class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy("blog:blog_list")


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/article_confirm_delete.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить статью "{{ object.title }}"?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        Удалить
                    </button>
                    <a class="btn btn-primary" href="{% url 'catalog:blog_list' %}" role="button">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'distribution/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card shadow-sm">
                    <img class="card-img-top" src="{{ object.preview_image | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ object.title }}</p>
                        <p>{{ object.content }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-body-secondary">Добавлено: {{ object.updated_at }}</small>
                            <small class="text-body-secondary">Количество просмотров: {{ object.views_counter }}</small>
                        </div>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'blog:article_update' object.pk %}"
                               role="button">Редактировать</a>
                            <a class="btn btn-primary" href="{% url 'blog:article_delete' object.pk %}"
                               role="button">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'distribution/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h1 class="display-4">Статьи</h1>
        <a class="btn btn-primary" href="{% url 'blog:article_create' %}"
           role="button">Добавить статью!</a>
        <p class="lead">Все публичные статьи на сайте:</p>
        <hr class="my-4">
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for article in object_list %}
            {% if article.is_published %}
            <div class="col">
                <div class="card shadow-sm">
                    <img class="card-img-top" src="{{ article.preview_image | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ article.title }}</p>
                        <p>{{ article.content | truncatechars:100 }}</p>
                        <small class="text-body-secondary">Дата публикации: {{ article.published_at }}</small>
                        <small class="text-body-secondary">Количество просмотров: {{ article.views_counter}}</small>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'blog:article_detail' article.pk %}"
                               role="button">Посмотреть</a>
                            <a class="btn btn-primary" href="{% url 'blog:article_update' article.pk %}"
                               role="button">Редактировать</a>
                            <a class="btn btn-primary" href="{% url 'blog:article_delete' article.pk %}"
                               role="button">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}