blog/urls.py
from django.urls import path
from blog.apps import BlogConfig

from blog.views import ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='blog_list'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('distribution.urls', namespace='distribution')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, email_verification, reset_password, UserListView, user_activity

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
    path('password-reset/', reset_password, name='reset_password'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('change/<int:pk>/', user_activity, name='change_is_active')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Электронная почта')
    avatar = models.ImageField(upload_to='users/users_avatars/', blank=True, null=True, verbose_name='Аватар')
    phone = models.CharField(max_length=35, verbose_name='Телефон', blank=True, null=True)
    country = models.CharField(max_length=35, blank=True, null=True, verbose_name='Страна')

    token = models.CharField(max_length=100, verbose_name='Токен', blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        """Прова доступа для менеджера"""
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('can_view_users', 'Can see all users'),
            ('can_change_is_active', 'Can block users'),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from distribution.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

users/views.py
import secrets

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView

from users.forms import UserRegisterForm
from users.models import User

from config.settings import EMAIL_HOST_USER


class RegisterView(CreateView):
    """Контроллер для регистрации новых пользователей"""
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Валидация электронной почты через отправку письма с подтверждением"""
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save(update_fields=['token', 'is_active'])
        host = self.request.get_host()
        url = f'/http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение регистрации',
            message=f'Для подтверждения регистрации перейдите по ссылке: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    ordering = ['pk']


def email_verification(request, token):
    """Функция для активации пользователя после перехода по ссылке из письма"""
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def reset_password(request):
    """Функия для смены пароля пользователем, присылает случайный на указанную почту"""
    if request.method == 'POST':
        email = request.POST.get('email')
        user = get_object_or_404(User, email=email)
        password = User.objects.make_random_password()
        user.set_password(password)
        user.save()

        send_mail(
            subject='Восстановление пароля',
            message=f'Вы запрашивали обновление пароля. Ваш новый пароль: {password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        render(request, 'users/reset_password.html')
        return redirect(reverse("users:login"))

    return render(request, 'users/reset_password.html')


@login_required
def user_activity(request, pk):
    """Функция для смены активности пользователей(не получателей)"""
    user = get_object_or_404(User, pk=pk)
    if user.is_active:
        user.is_active = False
    elif not user.is_active:
        user.is_active = True
    user.save()

    return redirect(reverse('users:user_list'))

users/templates/users/login.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <h3 class="card-title">
                        Вход пользователя
                    </h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary mb-3">
                        Войти
                    </button>
                     <a href="{% url 'users:reset_password' %}" class="bnt btn-outline-primary mb-3">Сбросить пароль</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <h3 class="card-title">
                        Регистрация пользователя
                    </h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary mb-3">
                        Регистрация
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-4">
            <div class="card">
                <h3 class="card-title">
                    Изменение пароля
                </h3>
                <div class="card-body">
                    {% csrf_token %}
                     <p>Введите ваш Email</p>
                    <input type="email" name="email">
                    <button type="submit" class="btn btn-success">
                        Запросить новый пароль
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for user in object_list %}
            {% if user.is_superuser == False %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Пользователь: {{ user.email }}</p>
                        <div class="btn-group">
                            {% if user.is_active %}
                            <a class="btn btn-danger" href="{% url 'users:change_is_active' user.pk %}"
                               role="button">Отключить</a>
                            {% else %}
                            <a class="btn btn-success" href="{% url 'users:change_is_active' user.pk %}"
                               role="button">Включить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}