blog/urls.py
from django.urls import path
from blog.apps import BlogConfig

from blog.views import ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='blog_list'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('distribution.urls', namespace='distribution')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

distribution/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from distribution.apps import DistributionConfig
from distribution.views import MessageListView, DeliveryListView, DeliveryDetailView, DeliveryUpdateView, \
    DeliveryDeleteView, DeliveryCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView, ClientListView, \
    ClientDeleteView, ClientUpdateView, ClientDetailView, ContactsView, MessageCreateView, ClientCreateView, \
    SendAttemptListView, delivery_activity, DeliveryManagementView, IndexView

app_name = DistributionConfig.name

urlpatterns = [
    path('', cache_page(60)(IndexView.as_view()), name='index'),
    path('deliveries/', DeliveryListView.as_view(), name='delivery_list'),
    path('deliveries/create/', DeliveryCreateView.as_view(), name='delivery_create'),
    path('deliveries/<int:pk>/', DeliveryDetailView.as_view(), name='delivery_detail'),
    path('deliveries/<int:pk>/update/', DeliveryUpdateView.as_view(), name='delivery_update'),
    path('deliveries/<int:pk>/delete/', DeliveryDeleteView.as_view(), name='delivery_delete'),
    path('deliveries/management/', DeliveryManagementView.as_view(), name='manage_delivery'),
    path('change/<int:pk>/', delivery_activity, name='change_is_active'),

    path('messages/', MessageListView.as_view(), name='message_list'),
    path('messages/create', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('messages/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

    path('log/', SendAttemptListView.as_view(), name='log_list'),

    path('contacts/', ContactsView.as_view(), name='contacts'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, email_verification, reset_password, UserListView, user_activity

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
    path('password-reset/', reset_password, name='reset_password'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('change/<int:pk>/', user_activity, name='change_is_active')
]

distribution/models.py
from django.db import models

from users.models import User


class Client(models.Model):
    full_name = models.CharField(max_length=100, verbose_name='имя получателя')
    email = models.EmailField(verbose_name='электронная почта')
    comment = models.TextField(verbose_name='комментарий')

    owner = models.ForeignKey(User, verbose_name='автор рассылки', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.full_name}'

    class Meta:
        verbose_name = 'получатель'
        verbose_name_plural = 'получатели'


class Message(models.Model):
    theme = models.CharField(max_length=100, verbose_name='тема сообщения')
    content = models.TextField(verbose_name='содержание сообщения')

    owner = models.ForeignKey(User, verbose_name='автор рассылки', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'Тема: {self.theme}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Delivery(models.Model):
    STATUS_CHOICES = (
        ('CREATED', 'создана'),
        ('LAUNCHED', 'запущена'),
        ('COMPLETED', 'завершена'),
    )
    DELIVERY_PERIOD = (
        ('ONCE', 'однократно'),
        ('DAILY', 'ежедневно'),
        ('WEEKLY', 'еженедельно'),
        ('MONTHLY', 'ежемесячно'),
    )

    is_created = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    period = models.CharField(max_length=255, choices=DELIVERY_PERIOD, default='ONCE', verbose_name='периодичность')
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default='CREATED', verbose_name='статус рассылки')
    is_active = models.BooleanField(default=True, verbose_name='активная рассылка')

    message = models.ForeignKey(Message, on_delete=models.PROTECT, verbose_name='сообщение')
    email_client = models.ManyToManyField(Client, verbose_name='получатели')

    start_delivery = models.DateTimeField(verbose_name='начало рассылки')
    finish_delivery = models.DateTimeField(verbose_name='конец рассылки', blank=True, null=True)
    next_sending = models.DateTimeField(verbose_name='дата следующей рассылки', blank=True, null=True)

    owner = models.ForeignKey(User, verbose_name='автор рассылки', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'Рассылка №{self.pk}, {self.message}'

    class Meta:
        """Права доступа для менеджеров"""
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        permissions = [
            ('can_view_deliveries', 'Can see all deliveries'),
            ('can_edit_is_active', 'Can deactivate a delivery'),
        ]


class SendAttempt(models.Model):
    last_attempt = models.DateTimeField(verbose_name='Дата последней попытки', auto_now_add=True)
    status_attempt = models.BooleanField(verbose_name='Статус', default=False)
    server_answer = models.TextField(max_length=100, blank=True, null=True)
    delivery = models.ForeignKey(Delivery, on_delete=models.CASCADE, verbose_name='Рассылка', blank=True, null=True)
    client = models.TextField(max_length=100, blank=True, null=True)

    def __str__(self):
        return 'попытка отправки'

    class Meta:
        verbose_name = 'попытка'
        verbose_name_plural = 'попытки'

distribution/forms.py
from django import forms
from django.forms import ModelForm, ValidationError, BooleanField

from distribution.models import Delivery, Message, Client


class StyleFormMixin:
    """Миксин для стандартизации форм"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

            if isinstance(field.widget, forms.widgets.DateTimeInput):
                field.widget.input_type = 'datetime-local'


class DeliveryForm(StyleFormMixin, ModelForm):
    """Форма для рассылок"""
    class Meta:
        model = Delivery
        fields = "__all__"
        exclude = ['is_created', 'next_sending', 'owner']


class MessageForm(StyleFormMixin, ModelForm):
    """Форма для писем"""
    class Meta:
        model = Message
        fields = ['theme', 'content']

    def clean_theme(self):
        """Функции для контроля содержимого писем"""
        cleaned_data = self.cleaned_data.get('theme')

        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for each in forbidden_words:
            if each in cleaned_data:
                raise ValidationError('Извините, такая тема недопустима для сообщения')

        return cleaned_data

    def clean_content(self):
        """Функции для контроля содержимого писем"""
        cleaned_data = self.cleaned_data.get('content')

        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for each in forbidden_words:
            if each in cleaned_data:
                raise ValidationError('Извините, такое сообщение недопустимо для отправки')

        return cleaned_data


class ClientForm(StyleFormMixin, ModelForm):
    """Форма для получателей"""
    class Meta:
        model = Client
        fields = ['full_name', 'email', 'comment']

distribution/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView

from blog.models import Article
from distribution.forms import DeliveryForm, MessageForm, ClientForm
from distribution.models import Message, Delivery, Client, SendAttempt


class MessageListView(ListView):
    model = Message

    ordering = ['pk']


class MessageDetailView(DetailView):
    model = Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('distribution:message_list')

    def form_valid(self, form):
        """Установка создающего пользователя как владельца"""
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()

        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('distribution:message_list')

    def get_form_class(self):
        """Изменение объектов закрыто от не-владельцев"""
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return DeliveryForm
        raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('distribution:message_list')


class DeliveryListView(ListView):
    model = Delivery

    ordering = ['pk']


class DeliveryDetailView(LoginRequiredMixin, DetailView):
    model = Delivery


class DeliveryCreateView(LoginRequiredMixin, CreateView):
    model = Delivery
    form_class = DeliveryForm
    success_url = reverse_lazy('distribution:delivery_list')

    def form_valid(self, form):
        """Установка создающего пользователя как владельца, заполнение поля следующей отправки"""
        delivery = form.save()
        user = self.request.user
        delivery.owner = user
        delivery.next_sending = delivery.start_delivery
        delivery.save()

        return super().form_valid(form)


class DeliveryUpdateView(LoginRequiredMixin, UpdateView):
    model = Delivery
    form_class = DeliveryForm
    success_url = reverse_lazy('distribution:delivery_list')

    def get_form_class(self):
        """Изменение объектов закрыто от не-владельцев"""
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return DeliveryForm
        raise PermissionDenied


class DeliveryDeleteView(LoginRequiredMixin, DeleteView):
    model = Delivery
    success_url = reverse_lazy('distribution:delivery_list')


class ClientListView(ListView):
    model = Client

    ordering = ['pk']


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('distribution:client_list')

    def form_valid(self, form):
        """Установка создающего пользователя как владельца"""
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()

        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('distribution:client_list')

    def get_form_class(self):
        """Изменение объектов закрыто от не-владельцев"""
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return ClientForm
        raise PermissionDenied


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('distribution:client_list')


class ContactsView(TemplateView):
    template_name = 'distribution/contacts.html'


class SendAttemptListView(ListView):
    model = SendAttempt

    ordering = ['pk']


class DeliveryManagementView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    template_name = 'distribution/management_list.html'
    permission_required = 'distribution.can_view_deliveries'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['objects'] = Delivery.objects.all().order_by('pk')
        return context


@login_required
def delivery_activity(request, pk):
    """Функция для смены активности рассылки"""
    delivery = get_object_or_404(Delivery, pk=pk)
    delivery.is_active = not delivery.is_active
    delivery.save()
    return redirect(reverse('distribution:manage_delivery'))


class IndexView(TemplateView):
    template_name = 'distribution/index.html'

    def get_context_data(self, **kwargs):
        """Получение данных из ДБ о количестве рассылок и пользователей, а также случайных статей блога"""
        context = super().get_context_data(**kwargs)

        context['total_deliveries'] = Delivery.objects.count()
        context['total_clients'] = Client.objects.count()
        context['total_deliveries_is_active'] = Delivery.objects.filter(status__in=['CREATED', 'LAUNCHED'],
                                                                        is_active=True).count()
        context['articles'] = Article.objects.order_by('?')[:3]
        return context

distribution/templates/distribution/client_confirm_delete.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить получателя с именем {{ client.full_name }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        Удалить
                    </button>
                    <a class="btn btn-primary" href="{% url 'distribution:client_list' %}" role="button">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/client_detail.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ client.full_name }}</p>
                        <p>{{ client.email }}</p>
                        <p>{{ client.description }}</p>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'distribution:client_detail' client.pk %}"
                               role="button">Посмотреть</a>
                            <a class="btn btn-primary" href="{% url 'distribution:client_update' client.pk %}"
                               role="button">Редактировать</a>
                            <a class="btn btn-danger" href="{% url 'distribution:client_delete' client.pk %}"
                               role="button">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/client_form.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <h4 class="card-title">
                        {% if object %}
                        Изменение получателя {{ client.full_name }}
                        {% else %}
                        Создание нового получателя
                        {% endif %}
                    </h4>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary mb-3" >
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/contacts.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
{% endblock %}

distribution/templates/distribution/delivery_confirm_delete.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить рассылку от {{ delivery.is_created }} № {{ delivery.pk }}?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        Удалить
                    </button>
                    <a class="btn btn-primary" href="{% url 'distribution:delivery_list' %}" role="button">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/delivery_detail.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Рассылка от {{ delivery.is_created }} № {{ delivery.pk }}</p>
                        <p>Периодичность: {{ delivery.get_period_display }}</p>
                        <p>{{ delivery.message }}</p>
                        <p>Начало: {{ delivery.start_delivery }}</p>
                        <p>Конец: {{ delivery.finish_delivery }}</p>
                        <p>Статус: {{ delivery.get_status_display }}</p>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'distribution:delivery_detail' delivery.pk %}"
                               role="button">Посмотреть</a>
                            <a class="btn btn-primary" href="{% url 'distribution:delivery_update' delivery.pk %}"
                               role="button">Редактировать</a>
                            <a class="btn btn-danger" href="{% url 'distribution:delivery_delete' delivery.pk %}"
                               role="button">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/delivery_list.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <a class="btn btn-primary" href="{% url 'distribution:delivery_create' %}" role="button">Начать рассылку!</a>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for delivery in object_list %}
            {% if delivery.status == 'CREATED' or delivery.status == 'LAUNCHED' %}
            {% if user == delivery.owner %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="form-control">{{ delivery }}</h5>
                        <p>Периодичность: {{ delivery.get_period_display }}</p>
                        <p>{{ delivery.message }}</p>
                        <p>Начало: {{ delivery.start_delivery }}</p>
                        <p>Конец: {{ delivery.finish_delivery }}</p>
                        <p>Статус: {{ delivery.get_status_display }}</p>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'distribution:delivery_detail' delivery.pk %}"
                               role="button">Посмотреть</a>
                            <a class="btn btn-primary" href="{% url 'distribution:delivery_update' delivery.pk %}"
                               role="button">Редактировать</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/management_list.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h4>Управление рассылками</h4>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for delivery in objects %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="form-control">{{ delivery }}</h5>
                        <p>Статус: {{ delivery.get_status_display }}</p>
                        {% if delivery.is_active %}
                        <a class="btn btn-danger" href="{% url 'distribution:change_is_active' delivery.pk %}"
                           role="button">Отключить</a>
                        {% else %}
                        <a class="btn btn-success" href="{% url 'distribution:change_is_active' delivery.pk %}"
                           role="button">Включить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/message_detail.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ message.theme }}</p>
                        <p>Содержание: {{ message.content }}</p>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'distribution:message_detail' message.pk %}"
                               role="button">Посмотреть</a>
                            <a class="btn btn-primary" href="{% url 'distribution:message_update' message.pk %}"
                               role="button">Редактировать</a>
                            <a class="btn btn-danger" href="{% url 'distribution:message_delete' message.pk %}"
                               role="button">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/message_list.html
{% extends 'distribution/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <a class="btn btn-primary" href="{% url 'distribution:message_create' %}" role="button">Создать письмо</a>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for message in object_list %}
            {% if user == message.owner %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ message.theme }}</p>
                        <p>{{ message.content | truncatechars:100 }}</p>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'distribution:message_detail' message.pk %}"
                               role="button">Посмотреть</a>
                            <a class="btn btn-primary" href="{% url 'distribution:message_update' message.pk %}"
                               role="button">Редактировать</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/sendattempt_list.html
{% extends 'distribution/base.html' %}
{% block content %}
    <div class="container">
            <div class="col">
                <div class="card shadow-sm form-control">
                        <h5>История отправлений</h5>
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Дата отправки</th>
                                <th scope="col">Статус</th>
                                <th scope="col">Адрес клиента</th>
                                <th scope="col">Рассылка</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for attempt in object_list %}
                            <tr>
                                <th scope="row">{{ attempt.pk }}</th>
                                <td>{{ attempt.last_attempt }}</td>
                                <td>{{ attempt.get_status_attempt_display }}</td>
                                <td>{{ attempt.client }}</td>
                                <td>{{ attempt.delivery }}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                </div>
            </div>

        </div>
{% endblock %}